package:
  name: motmot.wxvalidatedtext
  version: "0.5.3"

source:
  fn: motmot.wxvalidatedtext-0.5.3.tar.gz
  url: https://pypi.python.org/packages/source/m/motmot.wxvalidatedtext/motmot.wxvalidatedtext-0.5.3.tar.gz
  md5: e60ede71844fc8a7e13817d6374e5a9b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - wxpython

  run:
    - python
    - wxpython

test:
  imports:
    - motmot
    - motmot.wxvalidatedtext

about:
  home: http://code.astraw.com/projects/motmot
  license: BSD
  summary: 'validated integer/float text entry field for wxPython'
