package:
  name: motmot.wxvideo
  version: "0.5.6"

source:
  fn: motmot.wxvideo-0.5.6.tar.gz
  url: https://pypi.python.org/packages/source/m/motmot.wxvideo/motmot.wxvideo-0.5.6.tar.gz
  md5: bc22af8d97d55f9853f639509661cff4

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - wxpython
    - motmot.imops

test:
  # Python imports
  imports:
    - motmot
    - motmot.wxvideo

about:
  home: http://code.astraw.com/projects/motmot
  license: BSD
  summary: 'wx viewer of image sequences'
